/*
================================================================================
                       CUSTOMER CONCENTRATION ANALYSIS
================================================================================

Project:
--------
Retail Analytics Data Warehouse

Purpose:
--------
Measures how much total revenue is generated by the highest-value customers.

Analysis:
---------
- Top 10 customer revenue contribution

================================================================================
*/

USE RetailAnalyticsDW_gold;


-- Top 10 customer revenue contribution

SELECT
    ROUND(
        SUM(top_10_cust_revenue)
        / NULLIF(
            (SELECT SUM(sales_amount) FROM fact_sales),
            0
        ) * 100,
        2
    ) AS top_10_customers_contribution_pct
FROM (
    SELECT
        dc.customer_id,
        SUM(fc.sales_amount) AS top_10_cust_revenue
    FROM fact_sales fc
    LEFT JOIN dim_customers dc
        ON fc.customer_key = dc.customer_key
    GROUP BY
        dc.customer_id
    ORDER BY
        top_10_cust_revenue DESC
    LIMIT 10
) t;
